# Generated by Django 3.2.16 on 2023-05-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Коментария', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('year',), 'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведении'},
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
