# Generated by Django 3.2.16 on 2023-05-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230513_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведении'},
        ),
    ]
