# Generated by Django 3.2.16 on 2023-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Коментария', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('year',), 'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведении'},
        ),
    ]
