# Generated by Django 3.2.16 on 2023-05-13 11:00

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[api.validators.validet_year], verbose_name='Год выпуска'),
        ),
    ]
