# Generated by Django 3.2.16 on 2023-05-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230512_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-year',), 'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведении'},
        ),
    ]
