# Generated by Django 3.2.16 on 2023-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230510_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='count_review',
            field=models.IntegerField(default=0, verbose_name='Колличество оевью'),
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
