# Generated by Django 3.2.16 on 2023-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishreg',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
