# Generated by Django 3.2.16 on 2023-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230510_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None, verbose_name='Рейтинг'),
        ),
    ]
