# Generated by Django 3.2.16 on 2023-05-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'year'), 'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведении'},
        ),
    ]
