# Generated by Django 3.2.16 on 2023-05-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230514_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='count_review',
        ),
        migrations.RemoveField(
            model_name='title',
            name='sum_score',
        ),
    ]
