# Generated by Django 3.2.16 on 2023-05-14 14:47

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20230514_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[api.validators.validet_year], verbose_name='Год выпуска'),
        ),
    ]
