# Generated by Django 3.2.16 on 2023-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_rename_categorie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
